[phases.setup]
nixPkgs = ["ffmpeg", "python3", "python3-pip", "libavcodec-extra"]
cmds = [
  "which ffmpeg",
  "ffmpeg -version"
]

[start]
cmd = "gunicorn app:app"

[variables]
PATH = "/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/bin" 